### ISSUE TITLE
Validators don't see custom I18n errors

### ISSUE THREAD

**Issue by jarosluv** [hanami/validations#129] opened 2017-06-06 14:39 UTC
There is problem with validation and custom errors.

Please, see gist: https://gist.github.com/jarosluv/b6868e13736fc4e1be1321a933adca92

It's error raised when using Schema in controller, but all is okay when calling Schema directly.

**Comment by BenBach** [comment] 2017-07-28 14:53
@jarosluv Were you able to solve this. I have the exact same issue. The customer error messages of my customer predicates aren't found

**Comment by jarosluv** [comment] 2017-07-31 11:39
@BenBach 

Hello, Ben!

With help of @flash-gordon, it was possible to got workaround:

```ruby
module Web::Controllers::Campaigns
  class Create
    ...
    params do
      configure do
        config.messages = :i18n
      end

      required(:campaign).schema(CampaignSchema)
    end
    ...
  end
end

CampaignSchema = Dry::Validation.Form do
  required(:title).filled

  validate correct_title?: :title do |title|
    TitleHandler.call(title)
  end
end
```

**Comment by juanibiapina** [comment] 2017-08-02 09:11
A simpler example would be:

```ruby
class Model
  include Hanami::Validations::Form

  predicate :whatever?, message: "doesn't work" do |current|
    current == "lol"
  end

  validations do
    required(:field).filled(:whatever?)
  end
end
```

```
Dry::Validation::MissingMessageError:
       message for whatever? was not found
```

**Comment by juanibiapina** [comment] 2017-08-02 10:30
Actually it might not be as simple. This Model class needs to be included somewhere else for the bug to appear:

```
required(:model).schema(Model)
```

**Comment by AlfonsoUceda** [comment] 2017-08-15 22:35
@juanibiapina you can fix it including predicates in Child class as workaround.

**Comment by AlfonsoUceda** [comment] 2017-08-15 22:47
@jarosluv thank you for reporting this and sorry for the late answer, we are working in the fix because the workaround is ok but it isn't good if you have to add in every action you use that schema.

**Comment by BenBach** [comment] 2017-10-26 12:00
@AlfonsoUceda Thanks. This is not fixed in hanami 1.1.0 right?

**Comment by AlfonsoUceda** [comment] 2017-10-26 12:01
@BenBach no sorry, but I wanted to fix it maybe for 1.1.1, just I need time :P

**Comment by BenBach** [comment] 2017-10-26 12:07
@AlfonsoUceda No problem at all.

I am just wondering how to do a workaround:

```
# frozen_string_literal: true

require 'hanami/validations'

module MyCompany::Predicates
  include Hanami::Validations::Predicates

  self.messages_path = 'config/errors.yml'

  predicate(:uuid?) do |input|
    !/[0-9a-f]{8}-
    [0-9a-f]{4}-
    [0-9a-f]{4}-
    [0-9a-f]{4}-
    [0-9a-f]{12}/x.match(input).nil?
  end
end

module Api::Controllers::Customers
  class Destroy
    include Api::Action


    params do
      predicates MyCompany::Predicates

      required(:id).filled(:str?, :uuid?)
    end
end
```

Do you maybe have a hint?

**Comment by AlfonsoUceda** [comment] 2017-10-27 15:58
I'll take a look this weekend ;)

**Comment by AlfonsoUceda** [comment] 2017-10-29 15:00
@BenBach Almost hehe, that message is because custom predicates need custom error messages, so you need to create a validator class and use the predicate inside the validator. The problem is because we have to improve that API.

```ruby
module MyPredicates
  include Hanami::Validations::Predicates

  self.messages_path = 'config/errors.yml'

  predicate(:uuid?) do |input|
    !/[0-9a-f]{8}-
    [0-9a-f]{4}-
    [0-9a-f]{4}-
    [0-9a-f]{4}-
    [0-9a-f]{12}/x.match(input).nil?
  end
end

class CustomValidator
  include Hanami::Validations
  predicates MyPredicates

  validations do
    required(:id).filled(:uuid?)
  end
end

module Web::Controllers::Home
  class Index
    include Web::Action

    params Signup

    def call(params)
      result = params.validate
    end
  end
end
```

Adapt it to your code and tell me if it works.

**Comment by jodosha** [comment] 2017-11-20 11:37
@BenBach Can you please verify? TYVM.

**Comment by rodrigopk** [comment] 2017-11-24 16:36
@jodosha @AlfonsoUceda Hi, I work on the same company as @BenBach.
I tested the solution proposed by @AlfonsoUceda, and it works like a charm.
Thanks for the help!

**Comment by BenBach** [comment] 2017-11-24 16:37
@AlfonsoUceda Thanks a lot!!

**Comment by AlfonsoUceda** [comment] 2017-11-24 16:38
Thanks both to use Hanami, we want to improve hanami validations because it is in our roadmap.

**Comment by jodosha** [comment] 2017-11-27 08:31
Folks, thank you all. I'm closing this. I also documented the usage: https://github.com/hanami/hanami.github.io/pull/418

**Closed by jodosha** 2017-11-27 08:31 UTC
Labels: bug, waiting

**Comment by xvonabur** [comment] 2018-01-07 00:06
@jodosha Hi! Just my two cents. There is still issue with inline predicates. The only way to use it with i18n errors is to add 
```ruby
params do
  configure do
    config.messages = :i18n
  end
end
```
to controller (as mentioned above). Is it true for master branches of `hanami` and `hanami-validations`? If so, I can send a PR to hanami docs to mention it, if you wish. I've lost so much time to figure it out, so I want to help others.
