### ISSUE TITLE
Upgrade to dry-validation v1.0 or remove dependency from Hanami

### ISSUE THREAD

**Issue by joelvh** [hanami/validations#173] opened 2019-05-18 04:30 UTC
I spend a lot of time today trying to upgrade hanami-validations to use dry-validation v1.0.0.rc3 with little success. It is possible to upgrade the dry-rb parts, but the predicate framework that Hanami created has an unclear upgrade path that I can tell.

This dependency is preventing me from upgrading ROM in my project, and I'm not using the models.

Could hanami-validations be made an optional dependency in Hanami? Is there work being done to prep hanami-validations for dry-validation v1.0.0?

Thanks.

**Comment by jodosha** [comment] 2019-06-27 07:10
The problem is that `hanami-validations` locked an old version of `dry-validation`, so the entire set of stable/latest gems from ROM/DRY can't be used right now in `hanami` 1.3.

:warning: Now, that solution cannot be pursued because, removing that dependency is a breaking change for `hanami`.

:bulb: What I propose here, is to release `hanami-model` and `hanami-validations` 2.0 soon. They would contain only the agreed discussion points (ROM 5, new syntax for repos). Then we can relax the gem dependencies for a new `hanami` release `1.3.4`: `gem "hanami-validations", "~> 1.3", "< 3"`. :

:dart: The goal is to make possible soon to use latest DRY/ROM gems, or to use directly ROM 5, if people don't like `hanami-model`. :arrow_right: The other discussion points for `hanami` (see https://github.com/orgs/rom-rb/projects/3), can be released as `hanami-model` 2.1 or 3, contextually with `hanami` 2.

What do you folks think? @joelvh @solnic @mereghost @flash-gordon @AlfonsoUceda

**Comment by AlfonsoUceda** [comment] 2019-06-27 07:25
I agree that we should relax hanami-validations restriction so people aren't attached to an old version of dry-validations ;)

**Comment by solnic** [comment] 2019-06-27 08:53
If it's feasible (implementation-wise) to make it work with both versions of hanami-validations then it sounds like a very good plan

**Comment by jodosha** [comment] 2019-07-03 12:22
Please have a look at https://github.com/hanami/validations/pull/180

**Comment by joelvh** [comment] 2019-07-20 06:55
Thanks @jodosha this is great! Looks good to me.

**Comment by jodosha** [comment] 2019-07-23 09:50
Fixed by https://github.com/hanami/validations/pull/180

**Closed by jodosha** 2019-07-23 09:50 UTC
